# Location of the master changelog
changeLogFile: src/main/resources/db/changelog/db.changelog-master.xml

# Database connection
url: jdbc:postgresql://localhost:5432/two_sided_platform
username: admin
password: admin123
driver: org.postgresql.Driver

# Classpath (JDBC driver JAR path)
classpath: lib/postgresql-42.7.5.jar

# Logging options
logLevel: info
logFile: liquibase.log

# Contexts and labels (optional)
contexts: dev
labels: version1

# Diff settings (optional, for comparing DB with entities)
referenceUrl: hibernate:spring:com.mehdi.twosidedplatform.model
referenceDriver: liquibase.ext.hibernate.database.connection.HibernateDriver
referenceUsername: sa
referencePassword:
